# Copy this file to .streamlit/secrets.toml and fill in real values

NOTION_API_KEY = "your-notion-integration-secret"
VENDORS_DB_ID = "your-vendors-db-id"
PARTS_DB_ID = "your-parts-db-id"
SCORES_DB_ID = "your-scores-db-id"
SECRET_KEY = "change-me" 